### ISSUE TITLE
Add new logo

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#14]
See https://github.com/SquaredLabs/nucore-uconn/wiki/Redesign-Mockups#overall-design-cheat-sheet. 

An image should be added and some text should be changed. The text is from `app_name`, whatever that is. 

Should this be implemented with a ViewHook or with an optional image? Part of this feature needs to go upstream.

- [x] Add image
- [x] Change text
- [ ] Set font style

**Comment by robstolarz** [comment]
Decided logo should be an optional image, like `app/assets/images/logo.jpg` is (except ours will actually be optional) and that the change should probably be PR'd

**Comment by robstolarz** [comment]
item 1 blocked on https://github.com/tablexi/nucore-open/pull/1559, still

**Comment by robstolarz** [comment]
Item 2 linked to https://github.com/SquaredLabs/nucore-uconn/pull/16

**Comment by robstolarz** [comment]
https://github.com/tablexi/nucore-open/pull/1559 was merged so item 1 is done

**Comment by ColinMcNeil** [comment]
This was pushed in https://github.com/tablexi/nucore-open/pull/1643
