### ISSUE TITLE
Builds on `master` fail CI

### ISSUE THREAD

**Issue by jhanggi** [SquaredLabs/nucore-uconn#28]
Example: https://circleci.com/gh/SquaredLabs/nucore-uconn/54

```
Sending report to https://codeclimate.com for branch master... bundler: failed to load command: report_coverage (/home/ubuntu/nucore-uconn/vendor/bundle/ruby/2.4.0/bin/report_coverage)
RuntimeError: HTTP Error: 401
  /home/ubuntu/nucore-uconn/vendor/bundle/ruby/2.4.0/gems/codeclimate-test-reporter-1.0.8/lib/code_climate/test_reporter/client.rb:70:in `post_results'
```

This step in the build process sends reports to CodeClimate. In order to do this, the `CODECLIMATE_REPO_TOKEN` environment variable needs to be set in circle. This token comes from a codeclimate account. We can discuss if you want to set up your own account. It should be free for open source projects.

Otherwise, for now you can remove that line from the `circle.yml` file (https://github.com/SquaredLabs/nucore-uconn/blob/master/circle.yml#L23)

I would also recommend removing the `deployment` section. That is a step that automatically deploys to a stage server on successful builds. We do that through capistrano (see `config/deploy.rb` and `config/deploy/staging.rb`). Currently, we only do this continuous deployment on the open source branch. For the school-specific ones we do manual deployments; this is largely because of firewall restrictions making it hard to deploy from Circle (p.s. Circle 2.0 is on the horizon, we just haven't gotten there yet.)

**Comment by robstolarz** [comment]
"fixed", says circle https://circleci.com/gh/SquaredLabs/nucore-uconn/128
