### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#29]
(See "A CIP of CIDER", page 6.)

A number of classes of text need to be established or redefined to match the design.

- [ ] Welcome Text
- [ ] Page Title
- [ ] Instrument Title
- [ ] Smaller Subtitle (Instrument)
- [ ] Smaller Subtitle (Daily View) [where is this one used?]
- [ ] Calendar Date [needs bootstrap/jQUI change]
- [ ] Static Title
- [ ] Body Text

**Comment by robstolarz** [comment]
Completed in https://github.com/tablexi/nucore-open/pull/1643

**Comment by jhanggi** [comment]
Just a hint, if you include "Closes SquaredLab/nucore-uconn#29" in your PR description, it will automatically close the issue when the PR gets merged. Or "Resolves".

https://help.github.com/articles/closing-issues-using-keywords/
