### ISSUE TITLE
"Usage" option should appear in dropdown when adding pricing rule to instruments

### ISSUE THREAD

**Issue by CourtAW** [SquaredLabs/nucore-uconn#35]
<img width="653" alt="screen shot 2018-09-11 at 12 15 22 am" src="https://user-images.githubusercontent.com/30299061/45337884-4c7fe600-b558-11e8-956d-a7992fc292d6.png"> 
Instrument rates should be able to be set for "usage", "reservation" and "overage". But as seen above, only option currently available is "reservation".

**Comment by jhanggi** [comment]
A relay is a physical piece of hardware that controls power. Here’s the one
they use commonly at NU: https://www.synaccess-net.com/np-02b/
