### ISSUE TITLE
Setting database name

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#42]
The person deploying the app should be able to set the name of the database the app should use.

**Comment by joshea0** [comment]
@robstolarz is this the database name inside MySQL? Or the name of the MySQL deployment to use? Or both?

**Comment by robstolarz** [comment]
I was mostly thinking about setting this bit up: https://github.com/SquaredLabs/nucore-uconn/blob/master/config/database.yml.mysql.template#L10-L16

Right now, if you've set it to be in development mode, it will always use `nucore_open_development` as the DB name...
