### ISSUE TITLE
Spacing changes: 2col

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#48]
# 2col
impact factor: 64
## Views
/facilities/:facility_id/:product/
/facilities/:facility_id/:product/:product_id/edit
/facilities/:facility_id/:product/:product_id/files?file_type=(.*)
/facilities/:facility_id/:product/:product_id/price_policies
/facilities/:facility_id/:product/:product_id/price_policies/:id/edit
/facilities/:facility_id/:product/:product_id/price_policies/new
/facilities/:facility_id/:product/:product_id/users/
/facilities/:facility_id/:product/:product_id/users/new
/facilities/:facility_id/:product/new
/facilities/:facility_id/accounts
/facilities/:facility_id/accounts/:account_id/account_users/user_search
/facilities/:facility_id/accounts/:account_id/members
/facilities/:facility_id/accounts/:account_id/statements
/facilities/:facility_id/accounts/:id
/facilities/:facility_id/accounts/:id/edit
/facilities/:facility_id/accounts_receivable
/facilities/:facility_id/bundles/:bundle_id/bundle_products
/facilities/:facility_id/bundles/:bundle_id/bundle_products/:id/edit
/facilities/:facility_id/bundles/:bundle_id/bundle_products/new
/facilities/:facility_id/disputed_orders
/facilities/:facility_id/edit
/facilities/:facility_id/facility_accounts(.:format)
/facilities/:facility_id/facility_accounts/:id/edit(.:format)
/facilities/:facility_id/facility_accounts/new(.:format)
/facilities/:facility_id/facility_users
/facilities/:facility_id/facility_users/:facility_user_id/map_user
/facilities/:facility_id/instruments/:instrument_id/offline_reservations/edit
/facilities/:facility_id/instruments/:instrument_id/offline_reservations/new
/facilities/:facility_id/instruments/:instrument_id/schedule
/facilities/:facility_id/instruments/:instrument_id/schedule_rules
/facilities/:facility_id/instruments/:instrument_id/schedule_rules/:id/edit
/facilities/:facility_id/instruments/:instrument_id/schedule_rules/new
/facilities/:facility_id/instruments/example-instrument/product_access_groups
/facilities/:facility_id/instruments/example-instrument/product_access_groups/:id/edit
/facilities/:facility_id/instruments/example-instrument/product_access_groups/new
/facilities/:facility_id/journals
/facilities/:facility_id/journals/:id
/facilities/:facility_id/journals/new
/facilities/:facility_id/manage
/facilities/:facility_id/movable_transactions
/facilities/:facility_id/notifications
/facilities/:facility_id/order_statuses
/facilities/:facility_id/order_statuses/:id/edit
/facilities/:facility_id/order_statuses/new
/facilities/:facility_id/price_groups
/facilities/:facility_id/products/:product_id/accessories
/facilities/:facility_id/statements
/facilities/:facility_id/statements/:id
/facilities/:facility_id/statements/new
/facilities/:facility_id/training_requests
/facilities/:facility_id/transactions
/facilities/:facility_id/users
/facilities/:facility_id/users/:id
/facilities/:facility_id/users/:id/edit
/facilities/:facility_id/users/:user_id/accounts
/facilities/:facility_id/users/:user_id/orders
/facilities/:facility_id/users/:user_id/orders
/facilities/:facility_id/users/:user_id/reservations
/facilities/:facility_id/users/new
/facilities/:facility_id/users/new_external
/journal_cutoff_dates
/journal_cutoff_dates/:id
/journal_cutoff_dates/new
/log_events

## References
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Active/Manage_EF/Instrument_Reservations.png
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Clean/Manage_EF/Instrument_Reservations.png
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Measure/Manage_EF/Instrument_Reservations.png
* https://cdn.core.uconn.edu/public/V5_Views/Mobile/Active/Manage_EF/Reservations_Side_Menu.png
* https://cdn.core.uconn.edu/public/V5_Views/Mobile/Clean/Manage_EF/Reservations_Side_Menu.png
* https://cdn.core.uconn.edu/public/V5_Views/Mobile/Measure/Manage_EF/Reservations_Side_Menu.png
* https://cdn.core.uconn.edu/public/V5_Views/Tablet/Clean/Manage_EF/Reservatinos_Instruments.png
* https://cdn.core.uconn.edu/public/V5_Views/Tablet/Measure/Manage_EF/Reservatinos_Instruments.png

**Comment by ColinMcNeil** [comment]
Currently in PR #1762

**Comment by ColinMcNeil** [comment]
This was merged with the nav changes.
