### ISSUE TITLE
Spacing Changes: tabbed

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#52]
# tabbed
impact factor: 15
## Views
/accounts/:account_id
/accounts/:account_id/statements
/facilities/:facility_id/:product/
/facilities/:facility_id/accounts/:account_id/statements
/facilities/:facility_id/accounts/:id
/facilities/:facility_id/bundles/:bundle_id/bundle_products
/facilities/:facility_id/orders
/facilities/:facility_id/reservations
/facilities/:facility_id/statements/:id
/facilities/:facility_id/users/:id
/facilities/:facility_id/users/:user_id/accounts
/facilities/:facility_id/users/:user_id/orders
/facilities/:facility_id/users/:user_id/orders
/facilities/:facility_id/users/:user_id/reservations
/orders

## References
* https://cdn.core.uconn.edu/public/V5_Views/General_Rules/Nav_Bar_and_Drop_Down.png
* https://cdn.core.uconn.edu/public/V5_Views/General_Rules/Cheat_Sheet_for_Styles_Copy_2.png

**Comment by ColinMcNeil** [comment]
Is this part of the navbar change that's already live?

**Comment by ColinMcNeil** [comment]
This is in with the nav changes which have been merged already.
