### ISSUE TITLE
Spacing changes: detail

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#54]
# detail
impact factor: 7
## Views
/accounts/:account_id
/facilities/:facility_id/accounts/:id
/facilities/:facility_id/manage
/facilities/:facility_id/orders/:order_id/order_details/:order_detail_id/reservations/:id
/facilities/:facility_id/statements/:id
/facilities/:facility_id/users/:id
/orders/:order_id/order_details/:order_detail_id/reservations/:id(.:format)

## References
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Clean/Manage_EF/Instrument_Details.png
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Measure/Manage_EF/Instrument_Details.png

**Comment by ColinMcNeil** [comment]
This is currently in with the typography changes, but we are using a darker label color as per TableXI's request
