### ISSUE TITLE
Spacing changes: search-helper

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#56]
# search-helper
impact factor: 5
## Views
/accounts/:account_id/account_users/new
/facilities/:facility_id/:product/:product_id/users/new
/facilities/:facility_id/accounts/:account_id/account_users/user_search
/facilities/:facility_id/users
/global_user_roles/search

## References
* https://cdn.core.uconn.edu/public/V5_Views/General_Rules/Buttons,_boxes,_bubbles_.png
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Clean/Manage_EF/Users.png
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Measure/Manage_EF/Users.png

**Comment by ColinMcNeil** [comment]
Currently in https://github.com/tablexi/nucore-open/pull/1787
