### ISSUE TITLE
Spacing changes: quantity

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#57]
# quantity
impact factor: 2
## Views
/orders/:id
/orders/cart

## References
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Clean/My_Orders/Cart.png
* https://cdn.core.uconn.edu/public/V5_Views/Desktop/Measure/My_Orders/Cart.png

**Comment by ColinMcNeil** [comment]
Currently in https://github.com/tablexi/nucore-open/pull/1787

**Comment by ColinMcNeil** [comment]
Currently in https://github.com/tablexi/nucore-open/pull/1787
