### ISSUE TITLE
Implement "Use" button

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#7]
- [ ] Change "Home" button to "Use" button
- [ ] Make it selected when in Use mode

https://github.com/SquaredLabs/nucore-uconn/wiki/Redesign-Mockups#tabular-view

**Comment by ColinMcNeil** [comment]
Currently on
https://github.com/SquaredLabs/nucore-uconn/tree/CIDER-26-USE
but have not pull requested yet

**Comment by robstolarz** [comment]
I've been thinking about this issue for some time now. Maybe instead of unconditionally removing the "Home" link from the link collection, only replace it with the "use" and "manage" buttons if the user has things to manage? That way users would just see "Home" as they usually would if they can't manage anything.

@oliviacrosby any thoughts?

**Comment by ColinMcNeil** [comment]
We should discuss this with tablexi, since we can't change the home button without breaking the tests.

**Comment by ColinMcNeil** [comment]
This has been merged to nucore
